### ISSUE TITLE
Add Robot Training Dataset

### ISSUE THREAD

**Issue by kpertsch** [luckyrobots/luckyrobots#47]
Hi guys, 
Congrats on the launch, the sim env looks great! Robot learning is in desperate need of high quality sim envs, so this is a great effort! 

Are you guys planning to open-source some dataset for policy training as well? Would make it easier to iterate on algorithms if we had sim env + dataset!

**Comment by devrim** [comment]
Thank you so much for your kind words! Regarding your question about open-sourcing datasets:

Yes, we’re definitely planning to collect and open-source datasets for policy training with permission from everyone who is willing to participate. Our goal is to provide a comprehensive package that includes:

	1.	A series of images and/or videos capturing various prompt executions (e.g., “turn on the stove”, “find where my cat is”).
	2.	A diverse range of scenarios to cover common tasks and interactions.

I also think that this will significantly help researchers developing more robust policies for sure. 

We’re so early in this process though, can't wait to do this together with you all!

**Comment by kpertsch** [comment]
Sweet! Ideally please also collect robot / teleoperator actions in the process, so we can train policies on them!
You can check out our collection of open-source robot datasets for some inspiration -- would be great to add your dataset there too once it's ready! :) 

https://robotics-transformer-x.github.io/
